server:
  port: 8081
  servlet:
    context-path: /data-transmission-tool
spring:
  datasource:
    url: jdbc:postgresql://172.17.17.237:15432/DTT
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: abc123
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 63791
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
mybatis-plus:
  type-aliases-package: cn.iceblue.core.pojo.entity.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jasypt:
  encryptor:
    password: aa

dtt:
  captchaType: math

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: X-Token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒, -1代表永不过期
  activity-timeout: 3600
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

