server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://172.17.17.237:15432/DTT
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: abc123
mybatis-plus:
  type-aliases-package: cn.iceblue.core.pojo.entity.*